#!/bin/bash

pyhep=$(echo $0 | /usr/bin/python2 -c \
    "import os.path; print os.path.dirname(os.path.dirname(os.path.realpath(raw_input())))")

export PYTHONPATH="${pyhep}/py:${PYTHONPATH}"
export PYTHONSTARTUP="${pyhep}/py/hep/interactive.py"

/usr/bin/python2 "$@"
