#!/usr/bin/python2

#-----------------------------------------------------------------------
# imports
#-----------------------------------------------------------------------

import hep.root
import sys

#-----------------------------------------------------------------------
# functions
#-----------------------------------------------------------------------

def listTree(tree, indent=0):
    print " " * indent + "%d rows" % len(tree)
    for column in tree.schema.columns:
        print " " * indent + " - %-24s = %s" % (column.name, column.type)


def listDir(root_file, dir_path="", indent=0):
    # Loop over directory elements in 'dir_path'.
    for name, title, class_name in root_file.listdir(dir_path):
        path = root_file.join(dir_path, name)
        label = "%s (%s)" % (name, title)
        print (" " * indent) + label \
              + (" " * (64 - indent - len(label))) + class_name
        # If it's a directory, list its contents recursively.
        if class_name == "TDirectory":
            listDir(root_file, path, indent + 1)
        elif class_name == "TTree":
            listTree(root_file.load(path), indent + 1)


#-----------------------------------------------------------------------
# script
#-----------------------------------------------------------------------

file = hep.root.open(sys.argv[1])
listDir(file)
